# Zipkin Service
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: ecommerce
spec:
  selector:
    app: zipkin
  ports:
    - port: 9411
      targetPort: 9411
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9411
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "384Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 9411
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: 9411
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
---
# Service Discovery (Eureka)
apiVersion: v1
kind: Service
metadata:
  name: service-discovery
  namespace: ecommerce
spec:
  selector:
    app: service-discovery
  ports:
    - port: 8761
      targetPort: 8761
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
    spec:
      containers:
        - name: service-discovery
          image: selimhorri/service-discovery-ecommerce-boot:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
          envFrom:
            - configMapRef:
                name: ecommerce-config
          resources:
            requests:
              memory: "384Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 120
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 150
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
---
# Cloud Config Server
apiVersion: v1
kind: Service
metadata:
  name: cloud-config
  namespace: ecommerce
spec:
  selector:
    app: cloud-config
  ports:
    - port: 9296
      targetPort: 9296
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config
  template:
    metadata:
      labels:
        app: cloud-config
    spec:
      containers:
        - name: cloud-config
          image: selimhorri/cloud-config-ecommerce-boot:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9296
          envFrom:
            - configMapRef:
                name: ecommerce-config
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "768Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9296
            initialDelaySeconds: 120
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9296
            initialDelaySeconds: 150
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3