apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE_NAME}
  namespace: ecommerce-dev
  labels:
    app: ${SERVICE_NAME}
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${SERVICE_NAME}
  template:
    metadata:
      labels:
        app: ${SERVICE_NAME}
        environment: development
    spec:
      containers:
        - name: ${SERVICE_NAME}
          image: ${DOCKER_REGISTRY}/${SERVICE_NAME}:dev-${IMAGE_TAG}
          ports:
            - containerPort: ${SERVICE_PORT}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://service-discovery.ecommerce-dev.svc.cluster.local:8761/eureka/"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: ${SERVICE_PORT}
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: ${SERVICE_PORT}
            initialDelaySeconds: 120
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
  namespace: ecommerce-dev
spec:
  selector:
    app: ${SERVICE_NAME}
  ports:
    - port: ${SERVICE_PORT}
      targetPort: ${SERVICE_PORT}
  type: ClusterIP