apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  SPRING_PROFILES_ACTIVE: "dev"
  JAVA_OPTS: "-Xms256m -Xmx512m"

  # Service Discovery
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-discovery.ecommerce.svc.cluster.local:8761/eureka/"

  # Cloud Config
  SPRING_CLOUD_CONFIG_URI: "http://cloud-config.ecommerce.svc.cluster.local:9296"
  SPRING_ZIPKIN_BASE_URL: http://zipkin:9411/

  # URLs de servicios para la comunicación interna
  USER_SERVICE_HOST: "http://user-service.ecommerce.svc.cluster.local:8700"
  PRODUCT_SERVICE_HOST: "http://product-service.ecommerce.svc.cluster.local:8500"
  ORDER_SERVICE_HOST: "http://order-service.ecommerce.svc.cluster.local:8300"
  FAVOURITE_SERVICE_HOST: "http://favourite-service.ecommerce.svc.cluster.local:8800"
  SHIPPING_SERVICE_HOST: "http://shipping-service.ecommerce.svc.cluster.local:8600"
  PAYMENT_SERVICE_HOST: "http://payment-service.ecommerce.svc.cluster.local:8400"