apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce-dev
  labels:
    environment: development
---
apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce-stage
  labels:
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce-prod
  labels:
    environment: production