
server:
  servlet:
    context-path: /user-service

spring:
  application:
    name: USER-SERVICE
  profiles:
    active:
    - dev
  jackson:
    serialization:
      indent-output: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost


