
version: '3'
services:
  shipping-service-container:
    image: selimhorri/shipping-service-ecommerce-boot:0.1.0dev
    ports:
      - 8600:8600
    environment:
      - SPRING_PROFILES_ACTIVE=dev



