server:
  port: 9296

spring:
  zipkin:
    base-url: ${SPRING_ZIPKIN_BASE_URL:http://localhost:9411/}
  application:
    name: CLOUD-CONFIG
  cloud:
    config:
      server:
        git:
          uri: ${GIT_REPO_URI:https://github.com/SelimHorri/cloud-config-server}
          clone-on-start: true
          timeout: 60
          skip-ssl-validation: false
          # Si necesitas autenticación, descomenta estas líneas:
          # username: ${GIT_USERNAME:}
          # password: ${GIT_PASSWORD:}
          # private-key: ${GIT_PRIVATE_KEY:}
          # passphrase: ${GIT_PASSPHRASE:}
          default-label: main
          search-paths: "{application}"
          repos:
            - name: microservices
              pattern: "*-service"
              uri: ${GIT_REPO_URI:https://github.com/SelimHorri/cloud-config-server}
              search-paths: "{application}"

resilience4j:
  circuitbreaker:
    instances:
      cloudConfig:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        wait-duration-in-open-state: 5s
        sliding-window-type: COUNT_BASED

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
