
server:
  port: 9296

spring:
  zipkin:
    base-url: http://localhost:9411/
  application:
    name: CLOUD-CONFIG
  cloud:
    config:
      server:
        git:
          uri: https://SelimHorri@dev.azure.com/SelimHorri/GitHub%20Opensource%20Projects/_git/cloud-config-server
          clone-on-start: true

