
name: Develop, on PUSH Java CI/CD of service-discovery, ecommerce-microservice-backend app

on:
  push:
    branches: [ develop ]

jobs:
  build_push:
    #needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Setup env variables for Docker
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker Login
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build Docker image for service-discovery Microservice
      run: docker build -f service-discovery/Dockerfile -t service-discovery:dev .
    - name: Push service-discovery image
      run: docker push selimhorri/service-discovery:dev


