name: Staging Pipeline

on:
  push:
    branches: [ staging ]
  workflow_dispatch:
    inputs:
      services:
        description: 'Services to deploy (comma-separated)'
        required: true
        default: 'order-service,payment-service,product-service,shipping-service,user-service'
      run_e2e_tests:
        description: 'Run E2E tests'
        type: boolean
        default: true

jobs:
  trigger-staging-pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [order-service, payment-service, product-service, shipping-service, user-service]
    steps:
      - name: Check if service should be deployed
        id: check-service
        run: |
          if [[ "${{ github.event.inputs.services }}" == *"${{ matrix.service }}"* ]] || [[ "${{ github.event_name }}" == "push" ]]; then
            echo "deploy=true" >> $GITHUB_OUTPUT
          else
            echo "deploy=false" >> $GITHUB_OUTPUT
          fi

      - name: Trigger Jenkins Staging Job
        if: steps.check-service.outputs.deploy == 'true'
        run: |
          curl -X POST \
            -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" \
            "${{ secrets.JENKINS_URL }}/job/${{ matrix.service }}-stage/build" \
            --data-urlencode json='{"parameter": [
              {"name":"BRANCH_NAME", "value":"'${GITHUB_REF_NAME}'"},
              {"name":"COMMIT_SHA", "value":"'${GITHUB_SHA}'"},
              {"name":"RUN_E2E_TESTS", "value":"'${{ github.event.inputs.run_e2e_tests || 'true' }}'"}
            ]}'

  post-deployment-tests:
    needs: trigger-staging-pipeline
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.run_e2e_tests != 'false' }}
    steps:
      - name: Wait for deployments
        run: sleep 300  # Wait 5 minutes for deployments

      - name: Trigger E2E Test Suite
        run: |
          curl -X POST \
            -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" \
            "${{ secrets.JENKINS_URL }}/job/e2e-tests-staging/build" \
            --data-urlencode json='{"parameter": [{"name":"ENVIRONMENT", "value":"staging"}]}'